name: Build and deploy ASP.Net Core app to Azure Web App - SocialMediaAppAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ./Backend --configuration Release

      - name: dotnet publish
        run: dotnet publish ./Backend -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Replace secrets in appsettings.json
        run: |
          sed -i 's|UseGitHubSecret:SMA_DB_CONNECTION_STRING|${{ secrets.SMA_DB_CONNECTION_STRING }}|g' ./Backend/appsettings.json
          sed -i 's|UseGitHubSecret:JWT_KEY|${{ secrets.JWT_KEY }}|g' ./Backend/appsettings.json
          sed -i 's|UseGitHubSecret:JWT_EXPIRE_DAYS|${{ secrets.JWT_EXPIRE_DAYS }}|g' ./Backend/appsettings.json
          sed -i 's|UseGitHubSecret:JWT_ISSUER|${{ secrets.JWT_ISSUER }}|g' ./Backend/appsettings.json
          sed -i 's|UseGitHubSecret:SMA_STORAGE_CONNECTION_STRING|${{ secrets.SMA_STORAGE_CONNECTION_STRING }}|g' ./Backend/appsettings.json
          sed -i 's|UseGitHubSecret:SMA_BLOB_NAME|${{ secrets.SMA_BLOB_NAME }}|g' ./Backend/appsettings.json

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SocialMediaAppAPI'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3A3766E772D449D2BAA805AA37872B3D }}
